parsec-labs/acebusters-frontend

app/components/Notifications/Notification.js
=> Fix transaction info on notification in FireFox

app/components/TableMenu/index.js
=> disable sit-in button if user stack is empty

app/components/Dashboard/SectionReceive.js
=> display dashboard address with checksum

app/containers/Dashboard/reducer.js
=> clear dashboard store on logout

app/components/Dropdown/index.js, app/containers/App/actions.js, app/containers/App/index.js, app/containers/App/reducer.js, app/containers/App/selectors.js, app/containers/App/tests/reducer.test.js, app/containers/Table/index.js
=> add backfrop option to modals

app/components/TableMenu/index.js, app/containers/ActionBar/index.js, app/containers/TableMenu/actions.js, app/containers/TableMenu/index.js, app/containers/TableMenu/reducer.js, app/containers/TableMenu/sagas.js, app/containers/TableMenu/selectors.js, app/routes.js
=> mute sounds

app/containers/Table/index.js
Probably fixes #681
I'm unable to reproduce it on sandbox/local, but there is the only theoretical reason for such behavior and I fixed it.
=> Do not show RebuyDialog after join

app/containers/RegisterPage/index.js
**marketing request 1:**
indicate that ref code is optional if it is optional. there are still support requests that ask about ref code
=> Indicate if refCode is optional

app/components/Dashboard/SectionReceive.js
#683 
@troggy can you check the text of warning?
=> Warning about tx fees in deposit section

app/app.config.js, app/containers/App/sagas/intercomSagas.js
=> Disable intercom for sandbox and staging

app/containers/Table/actions.js, app/containers/Table/index.js, app/containers/Table/reducer.js, app/containers/Table/sagas/index.js, app/containers/Table/sagas/loadTableSaga.js, app/containers/Table/selectors.js, app/containers/Table/tests/sagas.test.js
=> move table load and missing hands load to saga

package.json
Fixes https://github.com/acebusters/oracle-cashgame/issues/39
=> Fix table hangs when one of players back from sitout

app/components/Alert/index.js, app/components/Dashboard/Exchange.js
=> Fix alerts layout

app/containers/GeneratePage/index.js, app/containers/RegisterPage/captcha.js, app/containers/RegisterPage/index.js, app/containers/RegisterPage/sagas.js
=> customize interrupted connection error

app/app.config.js, app/containers/ActionBar/index.js, app/containers/Seat/index.js, app/containers/Table/index.js
#737
In waiting/dealing — 10 secs, otherwise — 40 secs
=> Changed bet timeout in the frontend according to the backend

app/containers/Table/selectors.js, app/containers/Table/tests/selectors.test.js
=> Disable join buttons when player reserving seat

app/app.config.js
the new one has this issue fixed https://github.com/acebusters/economy/pull/53
=> use updated controller

app/containers/GeneratePage/index.js, app/services/account.js
=> Resend confirmation link

app/components/TableMenu/index.js, app/components/TableMenu/styles.js, app/containers/Table/index.js, app/services/tableService.js
=> «Call an opponent» button

app/containers/AccountProvider/reducer.js, app/containers/AccountProvider/sagas/accountLoginSaga.js, app/containers/Dashboard/reducer.js
Discussion here: https://acebusters.slack.com/archives/C2XJMJR6V/p1508170085000632
=> Set signerAddr, nickname and blocky on SET_AUTH instead of ACCOUNT_LOADED

app/components/Table/styles.js
Really hard to see it at the bottom
=> Show winners on table background

app/containers/Table/sagas/updateScannerSaga.js
https://github.com/acebusters/ab-web/issues/739
https://github.com/acebusters/event-worker/pull/41
=> Reset payedBlind flag on hand reset

app/containers/App/sagas/balancesLoadingSaga.js, app/containers/App/sagas/index.js
=> Preload balances on app load

app/containers/Seat/selectors.js, app/containers/Table/index.js, app/containers/Table/selectors.js, app/services/tableService.js, package.json
Resolves https://github.com/acebusters/oracle-cashgame/issues/43
=> Send beat requests from joined player each 1 min

app/components/Seat/Seat.js, app/containers/Seat/selectors.js
=> Show waiting status after sitting in

app/containers/Table/index.js
Sitout flag will be set on the backend
Should be merged after https://github.com/acebusters/oracle-cashgame/pull/46
=> Do not send sitout request before stand up

app/components/Dashboard/PowerDown.js, app/components/Dashboard/PowerUp.js, app/components/Dashboard/Wallet.js, app/containers/ExchangeDialog/index.js, app/containers/TransferDialog/index.js, app/utils/inputValidators.js
=> Fill up an amount field by link in the error message

app/containers/Table/index.js, app/containers/Table/messages.js
=> Show warning for stand-up in state > waiting

app/components/JoinDialog/index.js, app/containers/Table/index.js
=> Pass user's balance to JoinDialog

app/containers/LoginPage/index.js, app/containers/LoginPage/sagas.js
=> Reenable login form submit after password change

app/components/TableMenu/index.js
=> Allow «Call opponent» only for players and reenable it after 5 mins from request

app/services/wsProvider.js
=> Fix high CPU consumption on idle

app/components/Dashboard/CopyInput.js, app/components/Dashboard/LinkInput.js, app/components/Dashboard/Overview.js, app/components/Dashboard/Refs.js, app/components/Dashboard/styles.js, app/containers/Dashboard/messages.js
=> Show ref link on dashboard instead of ref code

app/components/CopyInput/index.js, app/components/CopyInput/styles.js, app/components/Dashboard/Refs.js, app/components/Dashboard/styles.js, app/components/Modal/DepositDialog.js
=> Use CopyInput for wallet address

app/app.config.js
new version allows multiple admins to create tables.
=> use new TableFactory for sandbox

app/app.config.js
New TableFactory with new tables.
Admins: me and @johannbarbie. Send me your rinkeby addresses if you want to admin this factory too.
=> using new TableFactory for sandbox

app/containers/TableDebug/index.js
=> Show link to table on etherscan in TableDebug

app/components/TableMenu/index.js, app/containers/Seat/selectors.js, app/containers/Table/selectors.js, app/containers/TableMenu/index.js
=> Disable «Call an opponent» button when table is full

app/components/Link/index.js, app/components/Modal/ConfirmDialog.js, app/containers/AccountProvider/index.js, app/containers/AccountProvider/sagas/websocketSaga.js, app/containers/AccountProvider/selectors.js, app/containers/AccountProvider/utils.js, app/containers/Notifications/constants.js, app/containers/Notifications/sagas/connectionNotificationsSaga.js, app/containers/Notifications/sagas/index.js, app/containers/Web3Alerts/NotConnected.js, app/containers/Web3Alerts/index.js
Resolves #808
- Restore websocket connection
- Force page refresh on navigation when connection is lost
- Replace «Connection lost» modal with notifications
=> Restore websocket connection

app/containers/Table/sagas/performBetSaga.js, app/containers/Table/sagas/updateScannerSaga.js
=> Fix no hole cards issue

app/components/TableMenu/index.js, app/containers/Table/index.js, app/containers/Table/selectors.js, app/containers/Table/tests/selectors.test.js, app/containers/TableMenu/index.js, app/utils/index.js
Resolves #819 
Resolves #681
Also, now dialog show when player's balance < bb instead of <= 0. We have that logic on backend and player was unable to continue the game because we didn't show rebuy dialog for him.
=> Fix rebuy false appearances

app/components/Table/styles.js, app/variables.js
=> Removed gradient from table background

app/components/JoinDialog/index.js, app/containers/TxSubmit/index.js, app/utils/makeCancelable.js
- Try to rerun estimate each 0.5s if estimate extremely high or not finished
- Show «Estimating gas» label on submit button instead of just disabling it
=>  TxSubmit improvements

app/components/Modal/ConfirmDialog.js, app/containers/ConfirmPage/index.js, app/containers/ConfirmPage/messages.js, app/containers/GeneratePage/index.js, app/containers/RegisterPage/sagas.js, app/services/account.js
=> Resend confirmation email from /confirm page

app/components/Dashboard/Exchange.js, app/components/Dashboard/Overview.js, app/containers/Dashboard/Exchange.js, app/containers/Dashboard/Overview.js, app/containers/Dashboard/messages.js, app/containers/Dashboard/selectors.js, app/containers/TxSubmit/index.js
Resolves #793
I put duplicate ETH payout form into Exchange tab and added a message about it to exchange form.
=> Explaining to users about ETH payout

app/containers/UpgradeDialog/index.js, app/containers/Web3Alerts/NoWeb3.js
=> Explanation about account unlock

app/containers/ActionBar/index.js, app/containers/Seat/index.js
Related to https://github.com/acebusters/oracle-cashgame/issues/49
=> Repeat turn sound signal when 1/2 of time is passed

app/components/Dashboard/Balances.js, app/components/Dashboard/Economy.js, app/components/Dashboard/Overview.js, app/components/Dashboard/SectionReceive.js, app/components/Modal/DepositDialog.js, app/containers/Dashboard/Overview.js, app/containers/Dashboard/index.js, app/containers/Dashboard/messages.js, app/routes.js
https://acebusters.slack.com/archives/C2XJMJR6V/p1515755843000172
=> Clean dashboard

app/app.config.js
- turned off production services
- redirected production domain to staging
- made params for staging and production the same in frontend
=> updated config for new domain

app/components/Dashboard/Advanced.js, app/components/Dashboard/styles.js, app/components/Header/index.js, app/components/Modal/styles.js, app/containers/AccountProvider/sagas/walletSagas.js, app/containers/Dashboard/Advanced.js, app/containers/Dashboard/actions.js, app/containers/Dashboard/index.js, app/containers/Dashboard/messages.js, app/containers/ExportDialog/index.js, app/containers/Header/index.js, app/containers/ImportDialog/index.js, app/routes.js
=> Import Export functions

app/components/Seat/StatusAction.js, app/components/Seat/styles.js
=> Show last player action only for 4 secs

app/components/ActionBar/FlagAmountBet.js
=> Improve bet input behavior

app/components/Seat/index.js, app/containers/Lobby/index.js, app/containers/Seat/index.js, app/containers/Table/actions.js, app/containers/Table/reducer.js, app/containers/Table/sagas/loadTableSaga.js, app/containers/Table/selectors.js, app/containers/TableDebug/index.js
=> Disable table join after first blind level passing
